// Generated by gencpp from file linear/MoveLinear.msg
// DO NOT EDIT!


#ifndef LINEAR_MESSAGE_MOVELINEAR_H
#define LINEAR_MESSAGE_MOVELINEAR_H

#include <ros/service_traits.h>


#include <linear/MoveLinearRequest.h>
#include <linear/MoveLinearResponse.h>


namespace linear
{

struct MoveLinear
{

typedef MoveLinearRequest Request;
typedef MoveLinearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLinear
} // namespace linear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::linear::MoveLinear > {
  static const char* value()
  {
    return "c348f8d8cd3a80f54328aa4159009109";
  }

  static const char* value(const ::linear::MoveLinear&) { return value(); }
};

template<>
struct DataType< ::linear::MoveLinear > {
  static const char* value()
  {
    return "linear/MoveLinear";
  }

  static const char* value(const ::linear::MoveLinear&) { return value(); }
};


// service_traits::MD5Sum< ::linear::MoveLinearRequest> should match
// service_traits::MD5Sum< ::linear::MoveLinear >
template<>
struct MD5Sum< ::linear::MoveLinearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::linear::MoveLinear >::value();
  }
  static const char* value(const ::linear::MoveLinearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::linear::MoveLinearRequest> should match
// service_traits::DataType< ::linear::MoveLinear >
template<>
struct DataType< ::linear::MoveLinearRequest>
{
  static const char* value()
  {
    return DataType< ::linear::MoveLinear >::value();
  }
  static const char* value(const ::linear::MoveLinearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::linear::MoveLinearResponse> should match
// service_traits::MD5Sum< ::linear::MoveLinear >
template<>
struct MD5Sum< ::linear::MoveLinearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::linear::MoveLinear >::value();
  }
  static const char* value(const ::linear::MoveLinearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::linear::MoveLinearResponse> should match
// service_traits::DataType< ::linear::MoveLinear >
template<>
struct DataType< ::linear::MoveLinearResponse>
{
  static const char* value()
  {
    return DataType< ::linear::MoveLinear >::value();
  }
  static const char* value(const ::linear::MoveLinearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LINEAR_MESSAGE_MOVELINEAR_H
