// Generated by gencpp from file linear/MoveLinearRequest.msg
// DO NOT EDIT!


#ifndef LINEAR_MESSAGE_MOVELINEARREQUEST_H
#define LINEAR_MESSAGE_MOVELINEARREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace linear
{
template <class ContainerAllocator>
struct MoveLinearRequest_
{
  typedef MoveLinearRequest_<ContainerAllocator> Type;

  MoveLinearRequest_()
    : command()  {
    }
  MoveLinearRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::linear::MoveLinearRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::linear::MoveLinearRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLinearRequest_

typedef ::linear::MoveLinearRequest_<std::allocator<void> > MoveLinearRequest;

typedef boost::shared_ptr< ::linear::MoveLinearRequest > MoveLinearRequestPtr;
typedef boost::shared_ptr< ::linear::MoveLinearRequest const> MoveLinearRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::linear::MoveLinearRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::linear::MoveLinearRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::linear::MoveLinearRequest_<ContainerAllocator1> & lhs, const ::linear::MoveLinearRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::linear::MoveLinearRequest_<ContainerAllocator1> & lhs, const ::linear::MoveLinearRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace linear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::linear::MoveLinearRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::linear::MoveLinearRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::linear::MoveLinearRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::linear::MoveLinearRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::linear::MoveLinearRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::linear::MoveLinearRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::linear::MoveLinearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::linear::MoveLinearRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::linear::MoveLinearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "linear/MoveLinearRequest";
  }

  static const char* value(const ::linear::MoveLinearRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::linear::MoveLinearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::linear::MoveLinearRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::linear::MoveLinearRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLinearRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::linear::MoveLinearRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::linear::MoveLinearRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINEAR_MESSAGE_MOVELINEARREQUEST_H
